### ISSUE TITLE
Coins do not show up in the world data

### ISSUE THREAD

**Issue by jzakrzewski** [firemark/battle-city-ai#22]
That means the only way to collect a coin is to accidentally drive onto one. I don't think it's correct.

**Comment by firemark** [comment]
Thank you - now is fixed.
![Image](https://i.ibb.co/7kSYPQj/x.png)
This is enough for you?

**Comment by jzakrzewski** [comment]
Yes, it comes as the part of the initial message, the destroy messages are also there.
Great, thanks.
